'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Aricie.DNN.Modules.PortalKeeper.UI

    Partial Public Class KeeperConfig

        '''<summary>
        '''divConfig control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divConfig As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''divDebug control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divDebug As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''cmdUpload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpload As Global.Aricie.DNN.UI.WebControls.UploadControl

        '''<summary>
        '''cmdDebug control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDebug As Global.DotNetNuke.UI.WebControls.CommandButton

        '''<summary>
        '''divHostConfig control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divHostConfig As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''KC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents KC As Global.Aricie.DNN.UI.WebControls.AriciePropertyEditorControl

        '''<summary>
        '''cmdClearProbes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdClearProbes As Global.DotNetNuke.UI.WebControls.CommandButton

        '''<summary>
        '''divPortalSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divPortalSettings As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSettings As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''KS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents KS As Global.Aricie.DNN.UI.WebControls.AriciePropertyEditorControl

        '''<summary>
        '''cmdSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSave As Global.DotNetNuke.UI.WebControls.CommandButton

        '''<summary>
        '''cmdCancelSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancelSettings As Global.DotNetNuke.UI.WebControls.CommandButton

        '''<summary>
        '''divUserBot control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divUserBot As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ctUserBotEntities control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctUserBotEntities As Global.Aricie.DNN.UI.WebControls.AriciePropertyEditorControl

        '''<summary>
        '''divUserBotCmds control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divUserBotCmds As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''divActionCommands control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divActionCommands As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblBotDefinition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBotDefinition As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ctlUserBot control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlUserBot As Global.Aricie.DNN.UI.WebControls.AriciePropertyEditorControl

        '''<summary>
        '''divInstall control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divInstall As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''cmdInstall control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdInstall As Global.DotNetNuke.UI.WebControls.CommandButton

        '''<summary>
        '''cmdUninstall control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUninstall As Global.DotNetNuke.UI.WebControls.CommandButton
    End Class
End Namespace
