'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Aricie.DNN.Modules.PortalKeeper.UI

    Partial Public Class Settings

        '''<summary>
        '''lblGeneralIntro control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblGeneralIntro As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ctS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctS As Global.Aricie.DNN.UI.WebControls.AriciePropertyEditorControl
    End Class
End Namespace
