'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :2.0.50727.3053
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.CodeDom.Compiler
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Xml

'
'This source code was auto-generated by xsd, Version=2.0.50727.3038.
'
Namespace Configuration

    '''<remarks/>
    <GeneratedCode("xsd", "2.0.50727.3038"), _
     Serializable(), _
     DebuggerStepThrough(), _
     DesignerCategory("code"), _
     XmlType(AnonymousType:=True), _
     XmlRoot([Namespace]:="", IsNullable:=False)> _
    Partial Public Class configuration

        Private nodesField() As configurationNodes

        '''<remarks/>
        <XmlElement("nodes")> _
        Public Property nodes() As configurationNodes()
            Get
                Return Me.nodesField
            End Get
            Set(ByVal value As configurationNodes())
                Me.nodesField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <GeneratedCode("xsd", "2.0.50727.3038"), _
     Serializable(), _
     DebuggerStepThrough(), _
     DesignerCategory("code"), _
     XmlType(AnonymousType:=True)> _
    Partial Public Class configurationNodes

        Private nodeField() As configurationNodesNode

        Private configfileField As String

        '''<remarks/>
        <XmlElement("node")> _
        Public Property node() As configurationNodesNode()
            Get
                Return Me.nodeField
            End Get
            Set(ByVal value As configurationNodesNode())
                Me.nodeField = value
            End Set
        End Property

        '''<remarks/>
        <Serialization.XmlAttribute()> _
        Public Property configfile() As String
            Get
                Return Me.configfileField
            End Get
            Set(ByVal value As String)
                Me.configfileField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <GeneratedCode("xsd", "2.0.50727.3038"), _
     Serializable(), _
     DebuggerStepThrough(), _
     DesignerCategory("code"), _
     XmlType(AnonymousType:=True)> _
    Partial Public Class configurationNodesNode

        Private anyField() As XmlElement

        Private pathField As String

        Private actionField As String

        Private keyField As String

        Private collisionField As String

        '''<remarks/>
        <XmlAnyElement()> _
        Public Property Any() As XmlElement()
            Get
                Return Me.anyField
            End Get
            Set(ByVal value As XmlElement())
                Me.anyField = value
            End Set
        End Property

        '''<remarks/>
        <Serialization.XmlAttribute()> _
        Public Property path() As String
            Get
                Return Me.pathField
            End Get
            Set(ByVal value As String)
                Me.pathField = value
            End Set
        End Property

        '''<remarks/>
        <Serialization.XmlAttribute()> _
        Public Property action() As String
            Get
                Return Me.actionField
            End Get
            Set(ByVal value As String)
                Me.actionField = value
            End Set
        End Property

        '''<remarks/>
        <Serialization.XmlAttribute()> _
        Public Property key() As String
            Get
                Return Me.keyField
            End Get
            Set(ByVal value As String)
                Me.keyField = value
            End Set
        End Property

        '''<remarks/>
        <Serialization.XmlAttribute()> _
        Public Property collision() As String
            Get
                Return Me.collisionField
            End Get
            Set(ByVal value As String)
                Me.collisionField = value
            End Set
        End Property
    End Class
End Namespace
