Namespace UI.WebControls
    Public Enum IconName
        'update Font Awesome version 4.2.0'
        None
        [Stop]
        [Try]
        Adjust
        Adn
        AlignCenter
        AlignJustify
        AlignLeft
        AlignRight
        Ambulance
        Anchor
        Android
        Angellist
        AngleDoubleDown
        AngleDoubleLeft
        AngleDoubleRight
        AngleDoubleUp
        AngleDown
        AngleLeft
        AngleRight
        AngleUp
        Apple
        Archive
        AreaChart
        ArrowCircleDown
        ArrowCircleLeft
        ArrowCircleODown
        ArrowCircleOLeft
        ArrowCircleORight
        ArrowCircleOUp
        ArrowCircleRight
        ArrowCircleUp
        ArrowDown
        ArrowLeft
        ArrowRight
        Arrows
        ArrowsAlt
        ArrowsH
        ArrowsV
        ArrowUp
        Asterisk
        At
        Backward
        Ban
        BarChartO
        Barcode
        Bars
        Beer
        Bell
        BellO
        BellSlash
        BellSlashO
        Bicycle
        Binoculars
        BirthdayCake
        Bitbucket
        BitbucketSquare
        Bold
        Bolt
        Book
        Bookmark
        BookmarkO
        Briefcase
        Btc
        Bug
        BuildingO
        Bullhorn
        Bullseye
        Bus
        Calculator
        Calendar
        CalendarO
        Camera
        CameraRetro
        CaretDown
        CaretLeft
        CaretRight
        CaretSquareODown
        CaretSquareOLeft
        CaretSquareORight
        CaretSquareOUp
        CaretUp
        Cc
        CcAmex
        CcDiscover
        CcMastercard
        CcPaypal
        CcStripe
        CcVisa
        Certificate
        ChainBroken
        Check
        CheckCircle
        CheckCircleO
        CheckSquare
        CheckSquareO
        ChevronCircleDown
        ChevronCircleLeft
        ChevronCircleRight
        ChevronCircleUp
        ChevronDown
        ChevronLeft
        ChevronRight
        ChevronUp
        Circle
        CircleO
        Clipboard
        ClockO
        Cloud
        CloudDownload
        CloudUpload
        Code
        CodeFork
        Coffee
        Cog
        Cogs
        Columns
        Comment
        CommentO
        Comments
        CommentsO
        Compass
        Compress
        Copyright
        CreditCard
        Crop
        Crosshairs
        Css3
        Cutlery
        Desktop
        DotCircleO
        Download
        Dribbble
        Dropbox
        Eject
        EllipsisH
        EllipsisV
        Envelope
        EnvelopeO
        Eraser
        Eur
        Exchange
        Exclamation
        ExclamationCircle
        ExclamationTriangle
        Expand
        ExternalLink
        ExternalLinkSquare
        Eye
        Eyedropper
        EyeSlash
        Facebook
        FacebookSquare
        FastBackward
        FastForward
        Female
        FighterJet
        File
        FileO
        FilesO
        FileText
        FileTextO
        Film
        Filter
        Fire
        FireExtinguisher
        Flag
        FlagCheckered
        FlagO
        Flask
        Flickr
        FloppyO
        Folder
        FolderO
        FolderOpen
        FolderOpenO
        Font
        Forward
        Foursquare
        FrownO
        FutbolO
        Gamepad
        Gavel
        Gbp
        Gift
        Github
        GithubAlt
        GithubSquare
        Gittip
        Glass
        Globe
        Google
        GooglePlus
        GooglePlusSquare
        GoogleWallet
        HandODown
        HandOLeft
        HandORight
        HandOUp
        HddO
        Headphones
        Heart
        HeartO
        Home
        HospitalO
        HSquare
        Html5
        Ils
        Inbox
        Indent
        Info
        InfoCircle
        Inr
        Instagram
        Ioxhost
        Italic
        Jpy
        Key
        KeyboardO
        Krw
        Laptop
        Lastfm
        LastfmSquare
        Leaf
        LemonO
        LevelDown
        LevelUp
        LightbulbO
        LineChart
        Link
        Linkedin
        LinkedinSquare
        Linux
        List
        ListAlt
        ListOl
        ListUl
        LocationArrow
        Lock
        LongArrowDown
        LongArrowLeft
        LongArrowRight
        LongArrowUp
        Magic
        Magnet
        MailReplyAll
        Male
        MapMarker
        Maxcdn
        Meanpath
        Medkit
        MehO
        Microphone
        MicrophoneSlash
        Minus
        MinusCircle
        MinusSquare
        MinusSquareO
        Mobile
        Money
        MoonO
        Music
        NewspaperO
        Outdent
        Pagelines
        PaintBrush
        Paperclip
        Pause
        Paypal
        Pencil
        PencilSquare
        PencilSquareO
        Phone
        PhoneSquare
        PictureO
        PieChart
        Pinterest
        PinterestSquare
        Plane
        Play
        PlayCircle
        PlayCircleO
        Plug
        Plus
        PlusCircle
        PlusSquare
        PowerOff
        Print
        PuzzlePiece
        Qrcode
        Question
        QuestionCircle
        QuoteLeft
        QuoteRight
        Random
        Refresh
        Renren
        Repeat
        Reply
        ReplyAll
        Retweet
        Road
        Rocket
        Rss
        RssSquare
        Rub
        Scissors
        Search
        SearchMinus
        SearchPlus
        Share
        ShareSquare
        ShareSquareO
        ShekelAlias
        SheqelAlias
        Shield
        ShoppingCart
        Signal
        SignIn
        SignOut
        Sitemap
        Skype
        Slideshare
        SmileO
        SoccerBallOAlias
        Sort
        SortAlphaAsc
        SortAlphaDesc
        SortAmountAsc
        SortAmountDesc
        SortAsc
        SortDesc
        SortNumericAsc
        SortNumericDesc
        Spinner
        Square
        SquareO
        StackExchange
        StackOverflow
        Star
        StarHalf
        StarHalfO
        StarO
        StepBackward
        StepForward
        Stethoscope
        Strikethrough
        Subscript
        Suitcase
        SunO
        Superscript
        Table
        Tablet
        Tachometer
        Tag
        Tags
        Tasks
        Terminal
        TextHeight
        TextWidth
        Th
        ThLarge
        ThList
        ThumbsDown
        ThumbsODown
        ThumbsOUp
        ThumbsUp
        ThumbTack
        Ticket
        Times
        TimesCircle
        TimesCircleO
        Tint
        ToggleOff
        ToggleOn
        Trash
        TrashO
        Trello
        Trophy
        Truck
        Tty
        Tumblr
        TumblrSquare
        Twitch
        Twitter
        TwitterSquare
        Umbrella
        Underline
        Undo
        Unlock
        UnlockAlt
        Upload
        Usd
        User
        UserMd
        Users
        VideoCamera
        VimeoSquare
        Vk
        VolumeDown
        VolumeOff
        VolumeUp
        Weibo
        Wheelchair
        Wifi
        Windows
        Wrench
        Xing
        XingSquare
        Yelp
        Youtube
        YoutubePlay
        YoutubeSquare


    End Enum
End NameSpace